FLAGS_FIELD = 'flags'
CLIENT_CONFIG = 'client_config'
RESOURCE_CONFIG = 'resource_config'
USE_EXTERNAL_RESOURCE = 'use_external_resource'
HOME_DIR_ENV_VAR = 'HOME'
CONFIG_DIR_ENV_VAR = 'XDG_CONFIG_HOME'
CACHE_DIR_ENV_VAR = 'XDG_CACHE_HOME'
DATA_DIR_ENV_VAR = 'XDG_DATA_HOME'

